version: '3.8'

services:
  appsmith:
    image: appsmith/appsmith-ee
    restart: always
    container_name: appsmith
    hostname: appsmith
    environment:
      # Database Configuration
      # - APPSMITH_DB_URL=mongodb://admin:admin@mongo:27017/appsmith?authSource=admin
      - APPSMITH_DB_URL=mongodb://admin:admin@mongo1:27017/appsmith?replicaSet=rs0&authSource=admin
      - APPSMITH_REDIS_URI=redis://redis:6379
      # Encryption Configuration
      - APPSMITH_ENCRYPTION_PASSWORD=alberto
      - APPSMITH_ENCRYPTION_SALT=arandomsalt

      # Application Settings
      - APPSMITH_INSTANCE_NAME=AppSmith

      # Security Settings
      - APPSMITH_SIGNUP_DISABLED=true
      - APPSMITH_ADMIN_EMAILS=oksbwn@gmail.com

      # Email Configuration
      # - APPSMITH_MAIL_ENABLED=true
      # - APPSMITH_MAIL_FROM=noreply@yourdomain.com
      # - APPSMITH_REPLY_TO=support@yourdomain.com
      # - APPSMITH_MAIL_HOST=smtp.yourdomain.com
      # - APPSMITH_MAIL_PORT=587
      # - APPSMITH_MAIL_SMTP_AUTH=true
      # - APPSMITH_MAIL_USERNAME=your_smtp_username
      # - APPSMITH_MAIL_PASSWORD=your_smtp_password
      # - APPSMITH_MAIL_TLS_ENABLED=true

      # S3/MinIO Configuration
      # - APPSMITH_S3_ACCESS_KEY=minio_access_key
      # - APPSMITH_S3_SECRET_KEY=minio_secret_key
      # - APPSMITH_S3_BUCKET_NAME=appsmith-bucket
      # - APPSMITH_S3_REGION=us-east-1
      # - APPSMITH_S3_ENDPOINT=http://minio:9000

      # OAuth Configuration (Google example)
      # - APPSMITH_OAUTH2_GOOGLE_CLIENT_ID=your-google-client-id
      # - APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET=your-google-client-secret

      # Custom Domain
      # - APPSMITH_CUSTOM_DOMAIN=app.yourdomain.com

      # Session Configuration
      - APPSMITH_SESSION_TIMEOUT=86400000 # 24 hours in milliseconds

      # Logging Configuration
      - APPSMITH_LOG_LEVEL=error

      # External API Request Timeout
      - APPSMITH_EXTERNAL_APIS_TIMEOUT=10000 # 10 seconds
    ports:
      - "8080:80"  # Expose Appsmith on port 8080
    depends_on:
      - mongo1
      - redis 
    volumes:
      - /docker/volumes/appsmith:/appsmith-stacks
    networks:
      - alberto

  mongo1:
    image: mongo:4.4
    restart: always
    container_name: mongo1
    hostname: mongo1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=appsmith
      - MONGO_REPLICA_SET_NAME=rs0  # Name of the replica set
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/data/configdb/mongodb-keyfile"]
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - /docker/volumes/mongo/data:/data/db  # MongoDB data 
      - ./mongodb-keyfile:/data/configdb/mongodb-keyfile:ro  # Mount the key file
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - alberto
   
  # mongo2:
  #   image: mongo:4.4
  #   container_name: mongo2
  #   hostname: mongo2
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #     - MONGO_INITDB_DATABASE=appsmith
  #     - MONGO_REPLICA_SET_NAME=rs0
  #   volumes:
  #     - /docker/volumes/mongo2/data:/data/db
  #     - /docker/volumes/mongo2/config:/data/configdb  
  #   networks:
  #     - alberto

  redis:
    image: redis:6
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    volumes:
      - /docker/volumes/redis/data:/data  # Redis data
    networks:
      - alberto

  postgres:
    image: postgres:14-alpine
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appsmith
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - /docker/volumes/postgres/data:/var/lib/postgresql/data  # PostgreSQL data
    networks:
      - alberto
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - /docker/volumes/pgadmin/data:/var/lib/pgadmin  # pgAdmin data
    networks:
      - alberto
  
  minio:
    image: minio/minio
    restart: always
    container_name: minio
    hostname: minio
    environment:
      - MINIO_ACCESS_KEY=YOUR_MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=YOUR_MINIO_SECRET_KEY
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - /docker/volumes/minio/data:/data  # MinIO data
    networks:
      - alberto

  duplicati:
    image: linuxserver/duplicati
    restart: always
    container_name: duplicati
    hostname: duplicati
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/volumes/appsmith:/source/appsmith
      - /docker/volumes/mongo:/source/mongo
      - /docker/volumes/redis:/source/redis
      - /docker/volumes/postgres:/source/postgres
      - /docker/volumes/minio:/source/minio
      - /docker/backups:/backups                   
    ports:
      - "8200:8200"
    networks:
      - alberto
      
networks:
  alberto:
    driver: bridge
